apiVersion: steward.sap.com/v1alpha1
kind: PipelineRun
metadata:
  generateName: ok-
spec:
  jenkinsFile:
    repoUrl: https://github.com/sap-production/demo-pipelines
    revision: master
    relativePath: success/Jenkinsfile
  logging:
    elasticsearch:
      runID: 1
