apiVersion: steward.sap.com/v1alpha1
kind: PipelineRun
metadata:
  generateName: details-
spec:
  jenkinsFile:
    repoUrl: https://github.com/sap-production/demo-pipelines
    revision: master
    relativePath: sleep/Jenkinsfile
  runDetails:
    jobName: myName
    sequenceNumber: 1
    cause: "my cause"
  logging:
    elasticsearch:
      runID: 1
