apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: steward-run
  labels:
    {{- include "steward.labels" . | nindent 4 }}
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default,runtime/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  allowPrivilegeEscalation: false
  runAsUser:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  seLinux:
    rule: 'RunAsAny'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  hostPorts: # do not allow host ports
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
