kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: steward-client
rules:
- apiGroups: ["steward.sap.com"]
  resources: ["tenants"]
  verbs: ["create","delete","get","list","patch","update","watch"]
