apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: steward-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  #TODO: Restrict permissions!
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: steward-system
  namespace: steward-system
