apiVersion: v1
kind: Namespace
metadata:
  # Specify namespace name here
  name: steward-c-client1
  annotations:

    # The unique prefix for tenant namespace names of this Steward client,
    # without a trailing '-' separator.
    steward.sap.com/tenant-namespace-prefix: steward-t-client1

    # The length of a random suffix of tenant namespace names of this Steward
    # client. Must be an integer in the range of [-127, 128]. Negative values
    # indicate that the default value should be used. Zero disabled the
    # random suffix. The system might limit the length to less than 128
    # characters.
    #
    # A tenant namespace name follows this schema:
    #
    #     <prefix>-<tenant_name>-<random>
    #
    # Example:
    #
    #     steward-t-client1-tenant1-f1a060
    #
    # [Optional; default="6"]
    #steward.sap.com/tenant-namespace-suffix-length: "6"

    # The ClusterRole to be assigned to the default service account of
    # tenant namespaces.
    # The ClusterRole itself is managed by Steward administrators.
    steward.sap.com/tenant-role: steward-tenant
