apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: steward-c-client1
  # Specify SAME namespace name as in Namespace resource above
  namespace: steward-c-client1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: steward-client
subjects:
- kind: ServiceAccount
  name: default
  # Specify SAME namespace name as in Namespace resource above
  namespace: steward-c-client1
